version: '3'

services:
  mongo-babilonia:
    image: mongo
    container_name: mongo-babilonia
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: babilonia
    volumes:
      - ./resources/mongodb:/docker-entrypoint-initdb.d
